### ISSUE TITLE
`numpy` version ceiling?

### ISSUE THREAD

**Issue by alberthli** [cmake-wheel/cmeel-boost#7]
Would it be possible for `cmeel-boost` to be upgraded to support later versions of `numpy`? I'm developing a package which has a dependency requiring `numpy>=1.26` and the requirements clash:
```
cmeel-boost 1.82.0 requires numpy<1.25,>=1.23, but you have numpy 1.26.1 which is incompatible.
```

**Comment by nim65s** [comment]
Hi @alberthli,
Thanks for opening this issue.

If I remember correctly (this information is super hard to find, or at least I'm not good at finding it when I need it), numpy 1.23 to 1.25 share the same ABI, but not 1.26, so this is not only a matter of bumping a number here for us.

This is already in my todolist, and goes with a bump of Boost to 1.83 (which also break ABI), and enable python 3.12 support.
But this will require some testing to ensure I won't break anything in the cmeel ecosystem in the process. 

But as you ask, I'll try to speed up on this task.
